require "amber_spec"
require "jennifer/adapter/postgres"
require "jennifer"
require "../src/controllers/**"
require "../src/mailers/**"
require "../src/models/**"
require "../src/helpers/**"
require "../config/*"
